// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OhunIslam.WebAPI.Infrastructure;

#nullable disable

namespace OhunIslam.WebAPI.Migrations
{
    [DbContext(typeof(MediaContext))]
    [Migration("20241209225416_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OhunIslam.WebAPI.Model.MediaItem", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MediaDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MediaLecturer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MediaPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MediaTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MediaId");

                    b.ToTable("MediaItems", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
