# version: '3.8'
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine
    hostname: localhost
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"  
      - "15672:15672" 
    networks:
      - ohunislam-network
    restart: always
networks:
  ohunislam-network:
    driver: bridge
#   ohunislam-api:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     container_name: ohunislam-api
#     restart: always
#     ports:
#       - "5000:8080" # API
#     depends_on:
#       - rabbitmq
#     environment:
#       RabbitMQ__Host: "localhost"
#       RabbitMQ__Username: "guest"
#       RabbitMQ__Password: "guest"
#     networks:
#       - ohunislam-network
