# version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"  # AMQP Protocol
      - "15672:15672" # management ui
    environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin
    networks:
      - ohunislam-network
  ohunislam-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ohunislam-api
    restart: always
    ports:
      - "5000:8080" # API
    depends_on:
      - rabbitmq
    environment:
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Username: "admin"
      RabbitMQ__Password: "admin"
    networks:
      - ohunislam-network
networks:
  ohunislam-network:
    driver: bridge